#!/bin/bash

syslog-ng

sysctl -p

iptables -t nat -A POSTROUTING -j MASQUERADE
iptables-save

if [ ! -e "/dev/net/tun" ] ; then
   mkdir /dev/net
   mknod /dev/net/tun c 10 200
fi;

exec openvpn /etc/openvpn/server.conf

